version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres-test
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=person-db
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - postgres-net

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - my-data:/var/lib/pgadmin
    networks:
      - postgres-net

volumes:
  db:
    driver: local
  my-data:

networks:
  postgres-net:
    external: false

